version: 3.7

services:
  app:
    build:
      context: .
    volumes:
      - ./:/rails-api-restful
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rails-api-restful
    command: "rails s -b 0.0.0.0 -p 3001"
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
